globals:
  - id: meter_read
    type: int
    restore_value: yes
    initial_value: "1800000"

esphome:
  name: "multical603"
  name_add_mac_suffix: false
  includes:
    - kmp.h
    - multical402.h

  project:
    name: casperghst42.multical603
    version: "1.0"

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret ha_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Multical 603 Fallback Hotspot"
    password: !secret ap_password

captive_portal:
    
web_server:
  port: 80

uart:
  id: ir 
  tx_pin: 17
  rx_pin: 16
  baud_rate: 1200
  stop_bits: 1

external_components:
  - source: github://oxan/esphome-stream-server

stream_server:
   uart_id: ir
   port: 3434

# Karmstrup Custom Sensor (first variable is update interval in ms; 3600000 is 1 hour)
# Reading every 30 minutes
# Value set at the top of the file (variable: meter_read)
custom_component:
  - lambda: |-
      auto Multical603 = new Multical402(
        id(meter_read),
        id(ir),
        id(m_energy),
        id(m_power),
        id(m_tin),
        id(m_tout),
        id(m_tdiff),
        id(m_flow),
        id(m_volume));
      App.register_component(Multical603);
      return {Multical603};
    components:
      - id: Multical603

sensor:
  #Karmstrup Custom Sensors
  - name: "Multical 603 Energy"
    platform: template
    id: m_energy
    icon: "mdi:lightning-bolt"
    unit_of_measurement: 'MWh' 
    accuracy_decimals: 0
    state_class: "total_increasing"
    device_class: "energy"

  - name: "Multical 603 Volume"
    platform: template
    id: m_volume
    unit_of_measurement: 'm3'
    accuracy_decimals: 2
    state_class: "measurement"

  - name: "Multical 603 Temperature In"
    platform: template
    id: m_tin
    icon: "mdi:thermometer"
    unit_of_measurement: '°C'
    accuracy_decimals: 2
    state_class: "measurement"
    device_class: "temperature"

  - name: "Multical 603 Temperature Out"
    platform: template
    id: m_tout
    icon: "mdi:thermometer"
    unit_of_measurement: '°C'
    accuracy_decimals: 2
    state_class: "measurement"
    device_class: "temperature"

  - name: "Multical 603 Temperature Diff"
    platform: template
    id: m_tdiff
    icon: "mdi:thermometer"
    unit_of_measurement: '°C'
    accuracy_decimals: 2
    state_class: "measurement"
    device_class: "temperature"

  - name: "Multical 603 Power"
    platform: template
    id: m_power
    icon: "mdi:flash"
    unit_of_measurement: 'kW'
    accuracy_decimals: 1
    state_class: "measurement"
    device_class: "power"

  - name: "Multical 603 Flow"
    platform: template
    id: m_flow
    unit_of_measurement: 'l/h'
    accuracy_decimals: 0
    state_class: "measurement"

  - platform: uptime
    name: "Multical 603 Uptime"
    update_interval: 60s
    
  - platform: wifi_signal
    name: "Multical 603 Wi-Fi Signal"
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Multical 603 IP Address"
    ssid:
      name: "Multical 603 Wi-Fi SSID"
    bssid:
      name: "Multical 603 Wi-Fi BSSID"
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
